-- Align submitter profile categories with the Phase 3 authorization model.
ALTER TYPE "SubmitterType" RENAME VALUE 'INDIVIDUAL' TO 'CITIZEN';
ALTER TYPE "SubmitterType" RENAME VALUE 'PANCHAYATI_RAJ_INSTITUTION' TO 'PANCHAYATI_RAJ';
ALTER TYPE "SubmitterType" RENAME VALUE 'COMMUNITY_ORGANIZATION' TO 'ORGANIZATION';
ALTER TYPE "SubmitterType" RENAME VALUE 'OTHER_ORGANIZATION' TO 'OTHER';
